name: CI Back-end with build compile and test in different jobs

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'sgcmapi/**'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile
        working-directory: sgcmapi/
        run: mvn compile 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Test
        working-directory: sgcmapi/
        run: mvn test
