name: CI Back-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'sgcmapi/**'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
  compile:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
      - name: Maven Compile
        working-directory: sgcmapi/
        run: mvn compile 
  test:
    needs: [build, compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
      - name: Maven Test
        working-directory: sgcmapi/
        run: mvn test
