name: CI Back-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'sgcmapi/**'
  workflow_call:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci-build-teste.yml@main
      - name: Maven Compile
        working-directory: sgcmapi/
        run: mvn compile 
  test:
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci-build-teste.yml@main
      - name: Maven Test
        working-directory: sgcmapi/
        run: mvn test
